//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public int Id { get; set; }
        public Nullable<int> IdCountry { get; set; }
        public Nullable<int> IdPicture { get; set; }
        public string NameHotel { get; set; }
        public string AboutHotel { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
